# Generated by Django 3.0.3 on 2020-02-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('idCalendar', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('head', models.IntegerField(blank=True, null=True)),
                ('tail', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('idSession', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('isClass', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('next_session', models.IntegerField()),
                ('previous_session', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarSession',
            fields=[
                ('idCalendarSession', models.AutoField(primary_key=True, serialize=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesiones.Calendar')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesiones.Session')),
            ],
        ),
    ]
