# Generated by Django 3.0.3 on 2020-02-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField()),
                ('tail', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('idSession', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('position', models.IntegerField()),
                ('next_session', models.IntegerField()),
                ('previous_session', models.IntegerField()),
            ],
        ),
    ]
