# Generated by Django 3.0.3 on 2020-02-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='isClass',
            field=models.BooleanField(default=True),
        ),
    ]
